---
title: Stock returns
author: Giuseppe Tinti Tomio
output:
    html_document:
        toc: true
        toc_float: true
        toc_collapsed: true
params:
    predictive_prior_observed_table: NULL
    predictive_prior_observed_plot: NULL
    observed_table: NULL
    observed_plot: NULL
    predictive_posterior_observed_table: NULL
    predictive_posterior_observed_plot: NULL
    parameter_table: NULL
    parameter_plots: NULL
---

```{r setup, include = FALSE}
# Set knitr options ------------------------------------------------------------
knitr::opts_chunk$set(
    echo = FALSE,
    fig.align = "center"
)

# Load packages ----------------------------------------------------------------
library(targets)

library(tidyverse)
library(gt)
library(DT)

# Source auxiliary R files -----------------------------------------------------
source("R/constants.R")
source("R/auxiliary_functions.R")
```

```{r common}
decimal_count <- tar_read(decimal_count)
```


# Predictive prior

```{r predictive prior observed table}
params$predictive_prior_observed_table %>%
    rename(.variable = variable) %>%
    select(
        Variable = .variable,
        Mean = mean,
        Median = median,
        MAD = mad,
        SD = sd,
        `CI 05%` = q5,
        `CI 95%` = q95
    ) %>%
    datatable(
        caption = htmltools::tags$caption(
            "Parameters",
            style = "text-align: center; font-size: 200%; color: black;",
        ),
        rownames = FALSE,
        filter = "top",
        options = list(lengthChange = FALSE, searching = FALSE)
    ) %>%
    formatPercentage(
        c("Mean", "Median", "SD", "MAD", "CI 05%", "CI 95%"),
        digits = decimal_count
    )
```

```{r predictive prior observed plot}
params$predictive_prior_observed_plot
```


# Exploratory analysis

```{r observed summary table}
params$observed_table %>%
    rename(.variable = variable) %>%
    select(
        Variable = .variable,
        Mean = mean,
        Median = median,
        MAD = mad,
        SD = sd,
        `CI 05%` = q5,
        `CI 95%` = q95
    ) %>%
    datatable(
        caption = htmltools::tags$caption(
            "Parameters",
            style = "text-align: center; font-size: 200%; color: black;",
        ),
        rownames = FALSE,
        filter = "top",
        options = list(lengthChange = FALSE, searching = FALSE)
    ) %>%
    formatPercentage(
        c("Mean", "Median", "SD", "MAD", "CI 05%", "CI 95%"),
        digits = decimal_count
    )
```

```{r observed plot}
params$observed_plot
```


# Predictive posterior

```{r predictive posterior observed table}
params$predictive_posterior_observed_table %>%
    rename(.variable = variable) %>%
    select(
        Variable = .variable,
        Mean = mean,
        Median = median,
        MAD = mad,
        SD = sd,
        `CI 05%` = q5,
        `CI 95%` = q95
    ) %>%
    datatable(
        caption = htmltools::tags$caption(
            "Parameters",
            style = "text-align: center; font-size: 200%; color: black;",
        ),
        rownames = FALSE,
        filter = "top",
        options = list(lengthChange = FALSE, searching = FALSE)
    ) %>%
    formatPercentage(
        c("Mean", "Median", "SD", "MAD", "CI 05%", "CI 95%"),
        digits = decimal_count
    )
```

```{r predictive posterior observed plot}
params$predictive_posterior_observed_plot
```


# Parameter posteriors

```{r parameter summary table}
params$parameter_table %>%
    filter(str_detect(.variable, "\\[.+\\]$", negate = TRUE)) %>%
    mutate(.variable = humanize_string(.variable)) %>%
    select(
        Variable = .variable,
        Mean = mean,
        Median = median,
        MAD = mad,
        SD = sd,
        `CI 05%` = q5,
        `CI 95%` = q95,
        Rhat = rhat,
        `ESS bulk` = ess_bulk,
        `ESS tail` = ess_tail
    ) %>%
    gt(rowname_col = "Variable") %>%
    fmt_percent(
        !c(Rhat, `ESS bulk`, `ESS tail`),
        decimals = decimal_count
    ) %>%
    fmt_percent(
        c(Rhat),
        decimals = 0
    ) %>%
    fmt_number(
        c(`ESS bulk`, `ESS tail`),
        decimals = 0
    ) %>%
    tab_spanner(
        "Statistics",
        !c(Rhat, `ESS bulk`, `ESS tail`)
    ) %>%
    tab_spanner(
        "MCMC",
        c(Rhat, `ESS bulk`, `ESS tail`)
    ) %>%
    tab_header("Parameter summaries")
```

```{r parameter table}
params$parameter_table %>%
    select(
        Variable = .variable,
        Mean = mean,
        Median = median,
        MAD = mad,
        SD = sd,
        `CI 05%` = q5,
        `CI 95%` = q95,
        Rhat = rhat,
        `ESS bulk` = ess_bulk,
        `ESS tail` = ess_tail
    ) %>%
    datatable(
        caption = htmltools::tags$caption(
            "Parameters",
            style = "text-align: center; font-size: 200%; color: black;",
        ),
        rownames = FALSE,
        filter = "top",
        options = list(lengthChange = FALSE, searching = FALSE)
    ) %>%
    formatPercentage(
        c("Mean", "Median", "SD", "MAD", "CI 05%", "CI 95%"),
        digits = decimal_count
    ) %>%
    formatPercentage(
        c("Rhat"),
        digits = 0
    ) %>%
    formatRound(
        c("ESS bulk", "ESS tail"),
        digits = 0
    )
```

```{r parameter plots}
for (plot in params$parameter_plots)
    print(plot)
```
